---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ambadran/public_html
    - /usr/bin/rsync -a --delete --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOYPATH
    # بديل لو /usr/bin/rsync غير موجود عند مزودك:
    # - /bin/rsync -a --delete --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOYPATH
